version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: center
      POSTGRES_PASSWORD: 123456123
      POSTGRES_DB: center
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U center -d center"]
      interval: 10s
      timeout: 5s
      retries: 5

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: app-center-db
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_DATABASE: center
  #     DB_USERNAME: center
  #     DB_PASSWORD: 123456123
  #   networks:
  #     - app-network

  # phppgadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phppgadmin
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 5432
  #     PMA_USER: center
  #     PMA_PASSWORD: 123456123
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
